export const mutation_types = {
  NEW_TODO: "NEW_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  SELECT_TODO: "SELECT_TODO",
  UPDATE_INPUT: "UPDATE_INPUT",
  GET_ALL_TODO: "GET_ALL_TODO",
  CLEAR_COMPLETED: "CLEAR_COMPLETED",
  SELECT_ALL_TODOS: "SELECT_ALL_TODOS",
};
